import { Router, Request, Response, NextFunction } from 'express';
import { User, Task, Note, Habit, FriendConnection } from './models';
import mongoose from 'mongoose';

const router = Router();

/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   AUTH MIDDLEWARE
   userId is sent as Bearer token (MongoDB ObjectId)
   â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */
const requireAuth = (req: Request, res: Response, next: NextFunction) => {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Unauthorized: No token provided' });
  }
  const userId = authHeader.split(' ')[1];
  if (!userId) {
    return res.status(401).json({ error: 'Unauthorized: Invalid token' });
  }
  (req as any).userId = userId;
  next();
};

/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   HELPER: build a partner response object from a User document
   Computes real stats from their habits & tasks in the DB
   â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */
async function buildPartnerPayload(friendUser: any, connectionId: string) {
  const fid = friendUser._id || friendUser.id;

  // Real habits & tasks for the friend
  const habits = await Habit.find({ userId: fid });
  const tasks = await Task.find({ userId: fid });

  const totalHabits = habits.length;
  const doneHabits = habits.filter(h => h.completedToday).length;
  const habitCompletion = totalHabits > 0 ? Math.round((doneHabits / totalHabits) * 100) : 0;

  const totalTasks = tasks.length;
  const doneTasks = tasks.filter(t => t.done).length;
  const taskCompletion = totalTasks > 0 ? Math.round((doneTasks / totalTasks) * 100) : 0;

  // weekProgress: last 7 days XP-like score (use streak as a proxy)
  const weekProgress = Array.from({ length: 7 }, (_, i) =>
    Math.max(0, Math.min(100, (friendUser.streak || 0) * 3 + (i % 3 === 0 ? 10 : -5)))
  );

  return {
    id: connectionId,                          // FriendConnection._id
    friendUserId: String(fid),
    name: friendUser.name,
    avatar: friendUser.avatar || null,
    level: friendUser.level || 1,
    xp: friendUser.xp || 0,
    streak: friendUser.streak || 0,
    longestStreak: friendUser.longestStreak || friendUser.streak || 0,
    status: 'online' as const,
    inviteCode: friendUser.inviteCode,
    habits: habits.map(h => ({ name: h.name, icon: h.icon, done: h.completedToday, streak: h.streak })),
    tasks: tasks.slice(0, 5).map(t => ({ title: t.title, done: t.done, priority: t.priority })),
    weekProgress,
    // Extended stats from user's self-reported fields
    healthScore: friendUser.healthScore || 50,
    careerScore: friendUser.careerScore || 50,
    productivityScore: friendUser.productivityScore || 50,
    focusHours: friendUser.focusHours || 0,
    studyHours: friendUser.studyHours || 0,
    codingHours: friendUser.codingHours || 0,
    waterIntake: friendUser.waterIntake || 0,
    sleepHours: friendUser.sleepHours || 7,
    exercise: friendUser.exercise || 0,
    currentChallenge: friendUser.currentChallenge || 'None',
    currentRank: friendUser.currentRank || 'Bronze I',
    mood: friendUser.mood || 'ðŸ˜ Okay',
    habitCompletion,
    taskCompletion,
    completedTasks: doneTasks,
    pendingTasks: totalTasks - doneTasks,
    weeklyGoalsDone: Math.min(doneTasks, 5),
    weeklyGoalsTotal: 5,
    monthlyGoalsDone: Math.min(doneTasks, 10),
    monthlyGoalsTotal: 10,
  };
}

/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   AUTH / PROFILE ENDPOINTS
   â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */
router.post('/auth/login', async (req: Request, res: Response) => {
  try {
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({ error: 'MongoDB connection is offline' });
    }
    const { email, name } = req.body;
    if (!email) return res.status(400).json({ error: 'Email is required' });

    let user = await User.findOne({ email });
    if (user) {
      return res.json(user);
    }

    // Create new user â€” inviteCode auto-generated by pre-save hook
    user = new User({
      name: name || 'New User',
      email,
      joinDate: new Date().toLocaleString('en-US', { month: 'long', year: 'numeric' }),
    });
    await user.save();
    res.status(201).json(user);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Server error during login' });
  }
});

router.get('/auth/profile', requireAuth, async (req: Request, res: Response) => {
  try {
    const user = await User.findById((req as any).userId);
    if (!user) return res.status(404).json({ error: 'User not found' });
    res.json(user);
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

router.put('/auth/profile', requireAuth, async (req: Request, res: Response) => {
  try {
    const user = await User.findByIdAndUpdate((req as any).userId, req.body, { new: true });
    if (!user) return res.status(404).json({ error: 'User not found' });
    res.json(user);
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   USER SEARCH â€” find user by invite code (for preview)
   â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */
router.get('/users/search', requireAuth, async (req: Request, res: Response) => {
  try {
    const code = (req.query.code as string || '').toUpperCase().trim();
    if (!code) return res.status(400).json({ error: 'code query param is required' });

    const userId = (req as any).userId;
    const me = await User.findById(userId);
    if (me?.inviteCode === code) {
      return res.status(400).json({ error: "That's your own invite code!" });
    }

    const targetUser = await User.findOne({ inviteCode: code });
    if (!targetUser) return res.status(404).json({ error: 'No user found with that invite code' });

    // Return limited public info
    res.json({
      id: targetUser._id,
      name: targetUser.name,
      avatar: targetUser.avatar,
      level: targetUser.level,
      streak: targetUser.streak,
      inviteCode: targetUser.inviteCode,
    });
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   TASKS ENDPOINTS
   â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */
router.get('/tasks', requireAuth, async (req: Request, res: Response) => {
  try {
    const tasks = await Task.find({ userId: (req as any).userId });
    res.json(tasks);
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

router.post('/tasks', requireAuth, async (req: Request, res: Response) => {
  try {
    const { title, note, category, priority, dueDate, dueTime, estimatedDuration, reminder, tags, recurring } = req.body;
    if (!title) return res.status(400).json({ error: 'Title is required' });

    const newTask = new Task({
      userId: (req as any).userId,
      title,
      note: note || '',
      category: category || 'Personal',
      priority: priority || 'medium',
      done: false,
      dueDate: dueDate || new Date().toISOString().split('T')[0],
      createdAt: new Date().toISOString().split('T')[0],
      dueTime, estimatedDuration, reminder, tags, recurring
    });
    await newTask.save();
    res.status(201).json(newTask);
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

router.put('/tasks/:id', requireAuth, async (req: Request, res: Response) => {
  try {
    const task = await Task.findOneAndUpdate(
      { _id: req.params.id, userId: (req as any).userId },
      req.body,
      { new: true }
    );
    if (!task) return res.status(404).json({ error: 'Task not found' });
    res.json(task);
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

router.delete('/tasks/:id', requireAuth, async (req: Request, res: Response) => {
  try {
    const task = await Task.findOneAndDelete({ _id: req.params.id, userId: (req as any).userId });
    if (!task) return res.status(404).json({ error: 'Task not found' });
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   NOTES ENDPOINTS
   â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */
router.get('/notes', requireAuth, async (req: Request, res: Response) => {
  try {
    const notes = await Note.find({ userId: (req as any).userId });
    res.json(notes);
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

router.post('/notes', requireAuth, async (req: Request, res: Response) => {
  try {
    const { title, body, color, pinned } = req.body;
    if (!title && !body) return res.status(400).json({ error: 'Title or body is required' });

    const newNote = new Note({
      userId: (req as any).userId,
      title: title || '',
      body: body || '',
      color: color || 'violet',
      pinned: pinned || false,
      createdAt: new Date().toISOString().split('T')[0],
    });
    await newNote.save();
    res.status(201).json(newNote);
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

router.put('/notes/:id', requireAuth, async (req: Request, res: Response) => {
  try {
    const note = await Note.findOneAndUpdate(
      { _id: req.params.id, userId: (req as any).userId },
      req.body,
      { new: true }
    );
    if (!note) return res.status(404).json({ error: 'Note not found' });
    res.json(note);
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

router.delete('/notes/:id', requireAuth, async (req: Request, res: Response) => {
  try {
    const note = await Note.findOneAndDelete({ _id: req.params.id, userId: (req as any).userId });
    if (!note) return res.status(404).json({ error: 'Note not found' });
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   HABITS ENDPOINTS
   â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */
router.get('/habits', requireAuth, async (req: Request, res: Response) => {
  try {
    const habits = await Habit.find({ userId: (req as any).userId });
    res.json(habits);
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

router.post('/habits', requireAuth, async (req: Request, res: Response) => {
  try {
    const { name, category, icon, priority, freq, target } = req.body;
    if (!name) return res.status(400).json({ error: 'Name is required' });

    const newHabit = new Habit({
      userId: (req as any).userId,
      name,
      category: category || 'Fitness',
      icon: icon || 'ðŸƒ',
      priority: priority || 'medium',
      freq: freq || 'Daily',
      streak: 0,
      target: target || '1 time',
      completedToday: false,
    });
    await newHabit.save();
    res.status(201).json(newHabit);
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

router.put('/habits/:id', requireAuth, async (req: Request, res: Response) => {
  try {
    const habit = await Habit.findOneAndUpdate(
      { _id: req.params.id, userId: (req as any).userId },
      req.body,
      { new: true }
    );
    if (!habit) return res.status(404).json({ error: 'Habit not found' });
    res.json(habit);
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

router.delete('/habits/:id', requireAuth, async (req: Request, res: Response) => {
  try {
    const habit = await Habit.findOneAndDelete({ _id: req.params.id, userId: (req as any).userId });
    if (!habit) return res.status(404).json({ error: 'Habit not found' });
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   FRIENDS / PARTNERS ENDPOINTS (Real system)
   â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */

/** GET /partners â€” return all connected friends with live stats */
router.get('/partners', requireAuth, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const connections = await FriendConnection.find({ userId });

    const partners = await Promise.all(
      connections.map(async (conn) => {
        const friendUser = await User.findById(conn.friendUserId);
        if (!friendUser) return null;
        return buildPartnerPayload(friendUser, String(conn._id));
      })
    );

    res.json(partners.filter(Boolean));
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Server error' });
  }
});

/** POST /partners/invite â€” connect to a friend by their invite code */
router.post('/partners/invite', requireAuth, async (req: Request, res: Response) => {
  try {
    const { code } = req.body;
    if (!code) return res.status(400).json({ error: 'Invite code is required' });

    const userId = (req as any).userId;
    const me = await User.findById(userId);

    // Cannot add yourself
    if (me?.inviteCode?.toUpperCase() === code.toUpperCase()) {
      return res.status(400).json({ error: "You cannot add yourself as a growth partner!" });
    }

    // Find the target user by their invite code
    const targetUser = await User.findOne({ inviteCode: code.toUpperCase() });
    if (!targetUser) {
      return res.status(404).json({ error: 'No user found with that invite code. Please check and try again.' });
    }

    // Check if already connected
    const alreadyConnected = await FriendConnection.findOne({
      userId,
      friendUserId: targetUser._id
    });
    if (alreadyConnected) {
      return res.status(400).json({ error: `You are already growth partners with ${targetUser.name}!` });
    }

    // Create the connection
    const conn = new FriendConnection({
      userId,
      friendUserId: targetUser._id,
      friendInviteCode: code.toUpperCase(),
      connectedAt: new Date().toISOString(),
    });
    await conn.save();

    // Return full partner payload with real stats
    const payload = await buildPartnerPayload(targetUser, String(conn._id));
    res.status(201).json(payload);
  } catch (error: any) {
    if (error.code === 11000) {
      return res.status(400).json({ error: 'Already connected with this user!' });
    }
    console.error(error);
    res.status(500).json({ error: 'Server error' });
  }
});

/** DELETE /partners/:id â€” disconnect from a friend */
router.delete('/partners/:id', requireAuth, async (req: Request, res: Response) => {
  try {
    const conn = await FriendConnection.findOneAndDelete({
      _id: req.params.id,
      userId: (req as any).userId
    });
    if (!conn) return res.status(404).json({ error: 'Connection not found' });
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

export default router;
